apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: create-pull-request-test-run-
spec:
  taskRef:
    name: create-pull-request
  params:
  - name: GIT_REPO_NAME
    value: 'gogs/coolstore-gitops'
  - name: SOURCE_BRANCH
    value: 'ci-mg494'
  - name: TARGET_BRANCH
    value: 'master'
  - name: GIT_SECRET_NAME
    value: 'gitea-secret'
  - name: GENERATE_PREVIEW_ENVIRONMENT
    value: 'true'