apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: patch-config-repo-run-
spec:
  taskRef:
    name: update-config
  workspaces:
  - name: input
    persistentVolumeClaim:
      claimName: config-source-pvc
  resources:
    inputs:
    - name: app-image
      resourceRef: 
        name: payment-image
  params:
  - name: IMAGE_TAG
    value: 'zsjcz'
  - name: PATH_CONTEXT
    value: 'kube'
  - name: GIT_SECRET_NAME
    value: gitea-secret
  - name: BRANCH_SUFFIX
    value: 'test-run'
