apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-pull-request
spec:
  params:
    - name: GIT_REPO_NAME
      description: The name of the repo to generate the pull request in (in format 'owner/repo')
    - name: TARGET_BRANCH
      description: The name of the branch to merge into (e.g. uat)
    - name: SOURCE_BRANCH
      description: The name of the branch where the changes are we'd like pulled into TARGET_BRANCH (e.g. ci-test)
    - name: TITLE_OVERRIDE
      description: Set this to something if you don't want the title of the pull request to be generated programmatically
      default: ""
    - name: COMMENT_OVERRIDE
      description: Set this to something if you don't want the body/comment of the pull request to be generated programmatically
      default: ""
    - name: GIT_SECRET_NAME
      description: The name of the secret that allows us to push to the git repo (in git credential-store format).  Key should be git.store
    - name: GENERATE_PREVIEW_ENVIRONMENT
      description: Whether to generate a preview environment from the pull request branch.  Default is false
      default: "false"
    - name: ARGO_CD_VERSION
      description: Version of the argocd container to run
      default: v1.7.4
  stepTemplate:
    envFrom:
      - configMapRef:
          name: argocd-env-configmap  # used for server address
      - secretRef:
          name: argocd-env-secret  # used for authentication (username/password or auth token)
    env:
      - name: PREVIEW_PROJECT
        value: preview-$(params.SOURCE_BRANCH)
  # results:
  #   - name: pull-request-id
  #     description: The id of the pull request created
  volumes:
    - name: git-secret
      secret:
        secretName: $(params.GIT_SECRET_NAME)
    - name: payload
      emptyDir: {}
  steps:
    - name: generate-payload-template
      image: quay.io/openshift/origin-cli:latest
      volumeMounts:
        - name: payload
          mountPath: /var/payload
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        TITLE=${TITLE_OVERRIDE:-}
        if [[ -z "${TITLE}" ]]; then
          TITLE="Tekton Change Request"
        fi

        COMMENT=${COMMENT_OVERRIDE:-}
        if [[ -z "${COMMENT}" ]]; then
          CURRENT_PIPELINE=$(oc get po/${HOSTNAME} -o jsonpath="{.metadata.labels['tekton\.dev/pipelineRun']}")
          COMMENT="Autogenerated changes from pipeline ${CURRENT_PIPELINE}"
          if [[ "$(params.GENERATE_PREVIEW_ENVIRONMENT)" == "true" ]]; then
            COMMENT="Preview Application URL: https://${ARGOCD_EXTERNAL_HOSTNAME}/applications/${PREVIEW_PROJECT}\n${COMMENT}"}
          fi
        fi

        cat <<EOF > /var/payload/payload_template.json
        {
          "base": "$(params.TARGET_BRANCH)",
          "head": "$(params.SOURCE_BRANCH)",
          "assignee": null,
          "assignees": null,
          "title": "${TITLE}",
          "body": "${COMMENT}",
          "labels": [],
          "milestone": null,
          "due_date": null
        }
        EOF
    - name: call-api
      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      volumeMounts:
        - name: payload
          mountPath: /var/payload
        - name: git-secret
          mountPath: /var/run/secrets/git
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }
        BASE_URL=$(urldecode $(cat /var/run/secrets/git/git.store))
        
        # FIXME: Debugging
        echo "BASE_URL is ${BASE_URL}"

        PAYLOAD_FILE=/var/payload/payload_template.json

        PULLREQUEST_API_URL="${BASE_URL}/api/v1/repos/$(params.GIT_REPO_NAME)/pulls"

        curl -X POST -H "Content-Type: application/json" -d @"${PAYLOAD_FILE}" ${PULLREQUEST_API_URL}
    - name: generate-preview-environment
      image: argoproj/argocd:$(params.ARGO_CD_VERSION)
      securityContext:
        # This container normally runs as argocd:argocd but if we don't make it part of the root group
        # it won't get access to the .kube in the tekton home directory since the first task ran as root
        # See also: https://github.com/tektoncd/pipeline/blob/main/docs/auth.md#unsuccessful-cred-copy-warning
        runAsGroup: 0
      script: |
        if [ $(params.GENERATE_PREVIEW_ENVIRONMENT) != "true" ]; then
          echo "Not generating a preview environment for pull request on $(params.SOURCE_BRANCH)"
          return 0
        fi

        if [ -z $ARGOCD_AUTH_TOKEN ]; then
          yes | argocd login $ARGOCD_SERVER --username=$ARGOCD_USERNAME --password=$ARGOCD_PASSWORD;
        fi

        # create the preview project for argo to clone into
        kubectl create ns ${PREVIEW_PROJECT}

        # NOTE: rights to pull in image from cicd project given the service account group

        # FIXME: hardcoded cicd project
        argocd app create ${PREVIEW_PROJECT} \
                --repo http://gitea.argocd-demo-cicd:3000/gogs/coolstore-gitops \
                --revision $(params.SOURCE_BRANCH) \
                --path kube \
                --dest-server https://kubernetes.default.svc \
                --dest-namespace ${PREVIEW_PROJECT} \
                --sync-policy automated \
                --upsert