apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: payment-pipeline-run-
spec:
  pipelineRef:
    name: payment-pipeline
  params:
  # uncomment these parameters if you want to point to the internal git repo, pointing external might
  # make iteration easier
  - name: GIT_REPO
    value: "http://gitea:3000/gogs/coolstore.git"
    #value: "http://gogs:3000/gogs/eventinghello.git"
    #value: "https://github.com/hatmarch/coolstore.git"
  - name: PATH_CONTEXT
    value: "payment-service"
  - name: CACHE_VOLUME
    value: cache-vol
  - name: SERVICE_NAME
    value: payment
  - name: KN_ACTION
    value: create
  - name: KN_ADDITIONAL_ARGS
    value:
      - -l
      - "app.kubernetes.io/part-of=focus"
      - -e 
      - "mp.messaging.outgoing.payments.bootstrap.servers=my-cluster-kafka-bootstrap.argocd-demo-support:9092"
  resources:
  - name: app-image
    resourceRef:
      name: payment-image
  workspaces:
  - name: local-workspace
    persistentVolumeClaim:
      claimName: workvol-pvc
  podTemplate:
    volumes:
    - name: cache-vol
      persistentVolumeClaim:
        claimName: cache-pvc
  timeout: 1h0m0s
    