apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jib-maven
spec:
  params:
  - name: DIRECTORY
    description: The directory containing the app, relative to the source repository root
    default: .
  - name: CACHE
    description: The name of the volume for caching Maven artifacts and base image layers
    default: empty-dir-volume
  - name: INSECUREREGISTRY
    description: Whether to allow insecure registry
    default: "false"
  - name: IMAGE_TAG
    description: tag to append to output image resources
    default: latest
  workspaces:
  - name: source
  resources:
    outputs:
    - name: image
      type: image
  results:
    - name: image-with-tag
      description: The full tag of the image that is built
  steps:
  - name: build-and-push
    image: gcr.io/cloud-builders/mvn
    command:
    - mvn
    - -B
    - compile
    - com.google.cloud.tools:jib-maven-plugin:build
    - -Duser.home=/tekton/home
    - -Djib.allowInsecureRegistries=$(params.INSECUREREGISTRY)
    - -Djib.to.image=$(resources.outputs.image.url):$(params.IMAGE_TAG)
    workingDir: $(workspaces.source.path)/$(params.DIRECTORY)
    volumeMounts:
    - name: $(params.CACHE)
      mountPath: /tekton/home/.m2
      subPath: m2-cache
    - name: $(params.CACHE)
      mountPath: /tekton/home/.cache
      subPath: jib-cache
  - name: store-results
    image: registry.access.redhat.com/ubi8/ubi-minimal:latest
    script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        echo "$(resources.outputs.image.url):$(params.IMAGE_TAG)" | tr -d "\n" | tee $(results.image-with-tag.path)


  volumes:
  - name: empty-dir-volume
    emptyDir: {}