---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook
spec:
  serviceAccountName: pipeline
  triggers:
    - name: coolstore-webhook
      bindings:
      - ref: gogs-triggerbinding
      template:
        name: payment-trigger-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webhook
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: webhook
spec:
  port:
    targetPort: http-listener
  to:
    kind: "Service"
    name: webhook
    weight: 100
