---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: payment-trigger-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: payment-pipeline-triggered-run-
      labels:
        tekton.dev/pipeline: payment-pipeline
    spec:
      pipelineRef:
        name: payment-pipeline
      params:
      - name: GIT_REPO
        value: $(params.gitrepositoryurl)
      - name: GIT_REVISION
        value: $(params.gitrevision)
      - name: GIT_MESSAGE
        value: $(params.message)
      - name: PATH_CONTEXT
        value: "payment-service"
      - name: CACHE_VOLUME
        value: cache-vol
      - name: SERVICE_NAME
        value: payment
      - name: KN_ADDITIONAL_ARGS
        value: 
          - -l
          - "app.kubernetes.io/part-of=focus"
          - -e 
          - "mp.messaging.outgoing.payments.bootstrap.servers=my-cluster-kafka-bootstrap.argocd-demo-support:9092"    
      resources:
      - name: app-image
        resourceRef:
          name: payment-image
      workspaces:
      - name: local-workspace
        persistentVolumeClaim:
          claimName: workvol-pvc
      - name: local-cache
        persistentVolumeClaim:
          claimName: cache-pvc
      podTemplate:
        volumes:
        - name: cache-vol
          persistentVolumeClaim:
            claimName: cache-pvc